---
title: "Analysis of serve-flation"
author: "Andrew Tredennick"
format: html
---

## Libraries

```{r libraries}
library(tidyverse)
library(here)
library(arrow)
library(brms)
library(tidybayes)
library(ggridges)
```


## Load and tidy serve speed data from *deuce* package

### Load data
```{r data}
serve_data <- read_parquet(here("data", "serve_data.parquet"))
```

### Filter data to WTA (Women's Tennis Association) Tour
```{r wta}
iga_points <- serve_data |>
  filter(str_detect(player1, "Swiatek") | str_detect(player2, "Swiatek")) |>
  filter(Speed_KMH > 0 & !is.na(Speed_KMH)) |>
  mutate(PointServer = case_when(
    PointServer == 1 ~ player1,
    PointServer == 2 ~ player2,
    TRUE ~ NA_character_
  )) |>
  dplyr::select(match_id, slam, year, server = PointServer, speed_kmh = Speed_KMH) |>
  mutate(server = case_when(
    str_detect(server, "Swiatek") ~ "iga",
    TRUE ~ "field")
  ) |>
  filter(year > 2020, slam %in% c("usopen", "wimbledon")) |>
  mutate(year = factor(year),
         server = factor(server, levels = c("iga", "field")))

# from On Cloud (ON) color pallette: https://www.on.com
color_map <- c("iga" = "#FC63CE", "field" = "#27414F")

ggplot(iga_points,
       aes(
         x = factor(year),
         y = speed_kmh,
         fill = server,
         color = server
       )) +
  geom_dotplot(
    binaxis = 'y',
    dotsize = 0.5,
    stackdir = 'center',
    position = position_dodge(0.7),
    alpha = 0.3
  ) +
  geom_boxplot(position = position_dodge(0.7),
               alpha = 0.2,
               width = 0.5) +
  facet_wrap( ~ slam, ncol = 1) +
  scale_color_manual(values = color_map) +
  scale_fill_manual(values = color_map) +
  labs(x = "Year", y = "First serve speed (km/h)") +
  theme_minimal()

fit <- brm(speed_kmh ~ server*year + slam, data = iga_points)
newdata <- tibble(server = unique(iga_points$server)) |>
  crossing(tibble(year = unique(iga_points$year))) |>
  crossing(tibble(slam = unique(iga_points$slam)))
preds <- add_epred_draws(newdata, object = fit)
deltas <- preds |>
  ungroup () |>
  dplyr::select(server, year, .epred, .draw) |>
  group_by(server, year, .draw) |>
  summarise(speed = mean(.epred), .groups = "drop") |>
  ungroup() |>
  pivot_wider(names_from = server, values_from = speed) |>
  mutate(delta = iga - field)

colors <- c("#D1D1D1", "#B8A89D", "#8E7F6C", "#707070") 
delta_plot <- ggplot(deltas, aes(x = delta, y = year, fill = year, group = year)) +
  geom_vline(aes(xintercept = 0), linetype = 2) +
  geom_density_ridges(alpha = 0.75, color = NA, bandwidth = 0.5) +
  scale_fill_manual(values = colors) +
  labs(
    x = "Iga's speed advantage (km/h)",
    y = NULL,
    caption = "\n\nPosterior predicitive distributions averaged over\nUS Open and Wimbledon serve speeds."
  ) +
  theme_minimal(base_size = 14) +
  guides(fill = "none") +
  theme(text = element_text(family = "raleway"),
        axis.title = element_text(face = "bold"))
ggsave(here("figures", "deltas.pdf"), plot = delta_plot, width = 6, height = 4)
```
